"use client";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { ThirdwebProvider } from "@thirdweb-dev/react";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const pageTitle = "Tikeey | NFT Event Tickets Marketplace";
const pageDescription = "Blockchain-powered application for NFT ticketing";

export default function RootLayout({ children }) {
  return (
    <ThirdwebProvider
      activeChain="mumbai"
      clientId="03ed6dc80620c178a1786170c8d5db39"
    >
      <html lang="en">
        <head>
          {/* Meta title */}
          <title>{pageTitle}</title>

          {/* Meta description */}
          <meta name="description" content={pageDescription} />
        </head>
        <body
          className={`${montserrat.className} bg-custom-background bg-cover`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ThirdwebProvider>
  );
}
